### ISSUE TITLE
Event Notification

### ISSUE THREAD

**Issue by a11apurva** [bennyhawk/Testing#18]
1. Logged in through account-1.
2. Bookmarked an event.
3. Logged out
4. Logged in through account-2.
5. Still receiving event notification of bookmarked event of account-1.

**Comment by bennyhawk** [comment]
Cannot remove notification once set

**Comment by bennyhawk** [comment]
notification removal done

The other one is very difficult to achieve... All the alarm intents are set with android system, not on the app, thats why... And i don't think its that necessary...
