### ISSUE TITLE
Bookmarked cards

### ISSUE THREAD

**Issue by a11apurva** [bennyhawk/Testing#5]
The bookmarked card should also be similar in structure as the hackathon's cards.
It should snow Title, place, date, and on tap the description should come up.

**Comment by bennyhawk** [comment]
@a11apurva If the bookmarked card is of similar structure, it will take up a lot of space on the top.

**Comment by a11apurva** [comment]
You can try keeping just the name, place,date and remove the tags and
picture. Let's see how it looks.

**Comment by bennyhawk** [comment]
I think we can close this issue now. The bookmarked tab looks sweet...
